
version: '3.5'

services:
  db_auth:
    container_name: db_auth
    ports:
      - "5438:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
    image: postgres:15.0-alpine3.16 