
version: '3.5'

services:
  db_auth:
    container_name: db_auth
    ports:
      - "5438:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
    image: postgres:15.0-alpine3.16
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_PASSWORD=root
      - PGADMIN_DEFAULT_EMAIL=latosh02@mail.ru
    ports:
      - "5050:80"    